version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: server-mysql 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: db_example
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
    networks:
      - mysql-net
    volumes:
      - mysql_data:/var/lib/mysql      
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - mysql-net
networks:
  mysql-net:
volumes:
  mysql_data:

